# Generated by Django 4.2.7 on 2023-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="category_images/"),
        ),
    ]
